Initial commit
stackabletech/regorule-operator pull request #1
Opened 2021-04-08 15:17 UTC by lfrancke

2021-04-09 13:11 UTC, lfrancke commented
This operator should be renamed to RegoOperator or RegoPolicyOperator I guess

2021-04-09 13:31 UTC, soenkeliebau requested changes
Left a few comments, mostly minor stuff, just the service bit needs fixing I think.

2021-04-09 13:31 UTC, soenkeliebau commented on operator/src/lib.rs
> +    let time = SystemTime::now()
Would it potentially make sense to sync this with the timestamp on the Kubernetes resource that triggered this rebuild? I can see both being useful..

2021-04-09 13:34 UTC, lfrancke commented on operator/src/lib.rs
> +    let time = SystemTime::now()
That seems like a sensible idea, yes.
I'm with you. Both have their merits. In reality it probably doesn't matter much.

2021-04-26 21:04 UTC, lfrancke commented on server/src/bin/generate_crd.rs
> +fn main() -> Result<(), Box<dyn Error>> {
See https://github.com/clux/kube-rs/issues/497 which would make this much easier. We could move the common functionality to the operator-rs

For now I'll leave it like this as it is more flexible.

2021-04-26 21:09 UTC, lfrancke commented on operator/src/lib.rs
> +    let time = SystemTime::now()
Turns out: There is no super trivial "last modified" timestamp.
https://github.com/kubernetes/kubernetes/issues/12430
Server-side apply added timestamps on a per-manager basis but that'd be a lot of extra logic.
In short: I'll keep it as is for now.

2021-04-28 11:24 UTC, soenkeliebau commented on server/src/bin/generate_crd.rs
> +fn main() -> Result<(), Box<dyn Error>> {
fine for me

2021-04-28 11:27 UTC, soenkeliebau commented
LGTM

2021-04-28 11:27 UTC, soenkeliebau approved these changes

2021-04-28 13:42 UTC, merged